version: "3.8"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: task_management_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
  redis:
    image: redis:latest
  celery:
    build: .
    command: celery -A task_management worker --loglevel=info
    depends_on:
      - redis
