# version: "3.8"
services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - kafka
    environment:
      - KAFKA_BROKER_URL=kafka:9092
    networks:
      - task_network

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: task_management_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - task_network

  redis:
    image: redis:latest
    networks:
      - task_network

  celery:
    build:
      context: .
    command: celery -A task_management worker --loglevel=info
    depends_on:
      - redis
      - kafka
    networks:
      - task_network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - task_network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - task_network
    healthcheck:
      test:
        [
          "CMD",
          "kafka-broker-api-versions",
          "--bootstrap-server",
          "localhost:9092",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  task_network:
    driver: bridge
